name: CI Pipeline

on:
  push:
    branches:
      - main # Executar em push na branch main
  pull_request:
    branches:
      - main # Executar em pull requests na branch main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Java (necessário para projetos Spring Boot)
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Tipo de JDK
          java-version: '17'     # Altere para a versão compatível com seu projeto

      # Cache Maven dependencies para acelerar builds futuros
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Build e execução de testes
      - name: Build and Test
        run: mvn clean test

      # Executar a aplicação (opcional, para verificar execução)
      - name: Run Application
        run: mvn spring-boot:run
